### ISSUE TITLE
Issues with the Discord Service

### ISSUE THREAD

**Issue by CypherNL** [TheGoddessInari/hamsket#112]
### Steps to reproduce

1. Add a Discord service tab
2.  Log in with your Discord service tab
3.  Browse through you Discord servers and use Discord as you do with the official app.
3.1. Also, try to have voice chat conversations for a long period of time (about 1 to 2 hours is enough i think)

### Expected behavior

Everything works as fine as the official app does.

### Actual behavior
Sometimes the discord tab freeze and most of the time to unfreeze it is to click with your right mouse button on the Discord tab and close the opened context menu. If you click on reload instead closing the menu, the Discord tab stays stuck on a white screen until you restart the application.

In Voice chat, sometimes uncommonly i get disconnected while the status bar is green or i can't hear one of the persons in the voice chat until i re-connect with the voice chat group. On an older 0.5.18 build i got RTC disconnections instead of the issue here above.

### ENVIRONMENT

> Rambox-OS: v0.5.18

> OS: Windows 10 1607 Enterprise LTSB

> Arch: x64

> BuildVersion: 61fa8c4 (grafted, HEAD, tag: nightly, origin/master) Sun, 7 Jul 2019 12:23:52 -0700

> Does this happen upstream: unknown as i haven't used the original Rambox CE with Discord.

**Comment by TheGoddessInari** [comment]
Try this with the new electron versions. I don't often have long voice conversations on Discord (because push-to-talk only works on the standalone version).

It's a *thing* that I wish I could convince Discord that it was effectively running the desktop client, or at least enable things like push to talk, but at the present time I haven't deeply investigated how to go about that.

**Comment by CypherNL** [comment]
I've updated to the latest nightly version which has electron 6.0.0. Let's see if i got the same problem on there.

**Comment by CypherNL** [comment]
So far i had one freeze but that could be hamsket loading something and unfroze when rightclicking something in the Discord window.
The RTC disconnections don't happen to me so far.

I think the issue has been fixed after updating. I will close this issue.
