### ISSUE TITLE
Select default browser

### ISSUE THREAD

**Issue by Ploppz** [TheGoddessInari/hamsket#113]
Whenever I press links, hamsket opens the link in Chromium. How can I make it open it in Firefox instead?

### ENVIRONMENT

> Rambox-OS: v0.5.18

> OS: Arch Linux

> Arch: x64

**Comment by TheGoddessInari** [comment]
This is dependent on your Desktop Environment, and not Hamsket.

It uses `shell.openExternal` from Electron. If your environment is setup correctly, it should use your desktop's default browser as set in preferences/xdg-open on Linux, etc. If not, then it's an Electron bug unfortunately.

**Comment by Ploppz** [comment]
Yes, it is resolved.
