### ISSUE TITLE
Better documentation on custom badge update JS

### ISSUE THREAD

**Issue by alien2003** [TheGoddessInari/hamsket#115]
I'm trying to make inverse.chat update badge and I don't know what should I put into custom Update JS and how it works. 

Can you provide any example of what should I do to make counter work?

**Comment by TheGoddessInari** [comment]
The injected javascript interacts with the document as if it is a part of it (so window.* works as expected), and can call the badge update function with a count for any direct notifications, and then indirect notifications.

So you want to identify any elements corresponding to a direct or indirect notification, then call the updateBadge function, usually every 3s.

The function signature is (depending on whether rambox-OS or Hamsket)

```
window.rambox.updateBadge = function(direct, indirect = 0)
```

**Comment by alien2003** [comment]
Thank you, clear

**Comment by TheGoddessInari** [comment]
I'll leave myself a note to add wiki links and write up some documentation.

**Comment by TheGoddessInari** [comment]
I finally added this to the wiki: https://github.com/TheGoddessInari/hamsket/wiki/Custom-badge-update-JS

I'll add a link to the box in-app in the near-future.
