### ISSUE TITLE
Mastodon logo is out of date.

### ISSUE THREAD

**Issue by ryliejamesthomas** [TheGoddessInari/hamsket#117]
Hamsket is using the old Mastodon logo, it would be nice to update it :)

Should be available in this archive: https://joinmastodon.org/press-kit.zip

I can do the PR if you wish, just wanted to make an issue first.

**Comment by TheGoddessInari** [comment]
See if the `mastodon-icon` branch looks right, eg, https://github.com/TheGoddessInari/hamsket/blob/mastodon-icon/resources/icons/mastodon.png
or if I should use the original pixel dimensions. :/

**Comment by TheGoddessInari** [comment]
I haven't gotten any response on this yet.

**Comment by ryliejamesthomas** [comment]
Apologies. I'm in no position to build and test.

Based on the image you've linked to it seems you've used the wrong icon (use `Logotype (Simple).svg`--the one with the 'm'), and flattened-off the sides too much; they should be rounded. Personally, I'm not bothered by the vertical squashing :)

**Comment by ryliejamesthomas** [comment]
Made a PR: https://github.com/TheGoddessInari/hamsket/pull/135

**Comment by TheGoddessInari** [comment]
Fixed by d4ed71c.
