### ISSUE TITLE
Teams not working correctly.

### ISSUE THREAD

**Issue by frankhommers** [TheGoddessInari/hamsket#120]
We need this fix in Hamsket as well:

https://github.com/ramboxapp/community-edition/pull/2370/commits/42be7f3a1ffe73db14858b56bcc787577f0c92cc

**Comment by jbwharris** [comment]
I'm glad I'm not the only one experiencing this. I had written off Rambox as a lost cause for Teams, thinking it might have something to do with my work's implementation of SSO. I'm seeing this problem in Rambox Pro, CE and Hamsket. I can log into Teams and it'll load on a new implementation/session, but as soon as I close the app or it has to refresh the window, it seems to just get stuck in an irretrievable white screen loop.

**Comment by TheGoddessInari** [comment]
Somehow this escaped my notice. Feel free to ping me while things are still this small.

Did anyone figure out a root cause? I'm not exactly a fan of these bizarre workarounds.

**Comment by jbwharris** [comment]
I didn't mention this, but I'm seeing this problem on a Mac, so seeing the same problem as what's happening on Linux. I traced through a few of those threads and seemed to be able to get it to work by deleting ~/Library/Application Support/Hamsket/Partitions/Teams_1 

I know that doesn’t solve the root issue, but did seem to be a workaround.

**Comment by ruiumbelino** [comment]
I'm using the latest nightly, and still have the blank page.
