### ISSUE TITLE
.

### ISSUE THREAD

**Issue by wefalltomorrow** [TheGoddessInari/hamsket#128]
.

**Comment by TheGoddessInari** [comment]
Well, I was literally **just** going to say, Rambox-OS are the 'legacy' releases under the old branding, Hamsket are the yet-to-be-stabilized releases. Currently the only difference is the `electron` version and some (pending) UI differences, but sooner or later I'll not keep backporting the service changes, likely when Hamsket is stable with all of the UI stuff (like spellcheck) added properly.
