### ISSUE TITLE
Telegram Tab does not set messages to unread if read.

### ISSUE THREAD

**Issue by Podden** [TheGoddessInari/hamsket#134]
1. Install Rambox OS
2. Setup Telegram Account
3. See unread messages, click on them, change tab, nothing sets them to "read" except replying.

Hamsket: v0.5.19
OS: Windows 10
Arch: x64
BuildVersion:  e630f2a (grafted, HEAD, tag: 0.5.19, origin/rambox-0.5)
Does this happen upstream: yes

**Comment by TheGoddessInari** [comment]
I'll try to look into this before the end of work today, but it seems like perhaps the `unread_js` needs updating, because the 0.5 branch never received the erroneous 461052b update, which caused things to often fail to to count notifications as read.

**Comment by rodneyrod** [comment]
Might be worth mentioning there's a new Telegram web client which is getting more updates and supports newer features than the current tdweb.

https://github.com/evgeny-nadymov/telegram-react is the project link, they have a demo server on https://evgeny-nadymov.github.io/telegram-react/

**Comment by TheGoddessInari** [comment]
I can't confirm this. Tried with 0.5.19 and 0.5.20. Is there a specific situation in which this occurs, like group vs. individual?

**Comment by Podden** [comment]
Installed the newest nightly, works now. Switched back to 5.19, doesn't work. I don't know what happened. I'm closing this :).
