### ISSUE TITLE
Migration to Hamsket from version before rename

### ISSUE THREAD

**Issue by schnittchen** [TheGoddessInari/hamsket#142]
Hello,

I installed Hamsket parallel to an earlier version from this repo, which was still named Rambox. I copied ~/.config/Rambox to ~/.config/Hamsket and started Hamsket.

There were no services configured.

Do I need to reconfigure everything from scratch?

**Comment by dd23** [comment]
There is a `rambox` sub-folder in `Partitions` that you might need to rename to `hamsket`.
`.config/Rambox/Partitions/rambox/` --> `.config/Hamsket/Partitions/hamsket/`

Just a guess. I have not tested this. I only had 3 services that I simply configured new when I moved to 0.6.

**Comment by schnittchen** [comment]
That works, thank you.
