### ISSUE TITLE
Endless "Please wait until we clear all." when removing a service

### ISSUE THREAD

**Issue by cdrage** [TheGoddessInari/hamsket#144]
### Steps to reproduce

1. Add a random service
2. Try to delete it
3. Comes up with  "Please wait until we clear all."

### Expected behavior

Deleting the service

### Actual behavior

Never ending loop of: Please wait until we clear all.

### ENVIRONMENT

> Hamsket: 
Nightly

> OS: 
Debian  10 / Buster

> Arch: x64 

> BuildVersion: 
Current nightly

> Does this happen upstream: yes, no, unknown, or N/A

No logs (via developer console) or anything. Nothing.

**Comment by jeffreyhyun** [comment]
Deleting the application and reinstalling persists the old data.

Could you at least tell us where to find the storage files to delete so we can start from a clean slate?

**Comment by cdrage** [comment]
Still not fixed :( Just tested against master and it still endlessly removes. @fizmat @TheGoddessInari

**Comment by fizmat** [comment]
Works for me on Arch, will check on Windows soon. Are you sure you didn't install the nightly from after the fix was merged into master, but before the nightly with the fix was released?
