### ISSUE TITLE
Can’t remove a service

### ISSUE THREAD

**Issue by 5moufl** [TheGoddessInari/hamsket#152]
### Steps to reproduce
1. Try to remove a service (MS teams)
2. Wait…

### Expected behavior
Service should be deleted

### Actual behavior
I left it do its thing overnight, still not removed

![image](https://user-images.githubusercontent.com/755140/70606970-ec19a180-1bfd-11ea-868a-642e8e09da2f.png)

### ENVIRONMENT

> Version: 0.6.0
> Platform: win32 (x64)
> Electron: 7.1.1
> Chromium: 78.0.3904.99
> Node: 12.8.1
> BuildVersion: 702230e (grafted, HEAD, tag: nightly, origin/master) Thu, 14 Nov 2019 15:22:25 -0800

> Does this happen upstream? unknown

**Comment by fizmat** [comment]
Does the today's nightly work for you? I think it was released after your report.

> BuildVersion: 84ef78f (grafted, HEAD, origin/master) Tue, 10 Dec 2019 03:00:35 -0800

**Comment by 5moufl** [comment]
Yup!

**Comment by TheGoddessInari** [comment]
fwiw, nightly was updated yesterday in the early morning, as it says. :P But glad the PR fixed this, anyhow.

**Comment by 5moufl** [comment]
yay, I had just updated the day before after a vacation, and I didn’t think there would be an update (I didn’t check :$) one day later!
Thanks!
