### ISSUE TITLE
Hangouts login fail

### ISSUE THREAD

**Issue by venaud** [TheGoddessInari/hamsket#154]
This issue is solved on Rambox-CE:
https://github.com/ramboxapp/community-edition/commit/83e7fd38d6859bd6d74b0348dd4c29a0c5f8b4b2

https://github.com/ramboxapp/community-edition/commit/1a5ff9c8d13f1528df7fec949e1061d299d15c6c

### Steps to reproduce

Log into hangouts

### Expected behavior

Logged into hangouts.

### Actual behavior

Error page "You are trying to sign in from a browser or app that doesn't allow us to keep your account secure"

### ENVIRONMENT

> Hamsket: v0.X.X

> OS: linux

> Arch: x64

> BuildVersion: fd21604

> Does this happen upstream: yes, no, unknown, or N/A

**Comment by munkymack** [comment]
This is actually an issue that seems to be affecting all google services (hangouts, voice, calendar and keep are the ones I've personally run into issues on)

**Comment by Venryx** [comment]
Happens for the Gmail service as well; makes the app unusable for me at the moment. (though it's okay short-term, since I'm using rambox-ce in the meantime)

**Comment by ljesus** [comment]
Same issue here

**Comment by houndmaster** [comment]
gmail service doesn't work either, it would be nice to have it working

**Comment by TheGoddessInari** [comment]
I'll push on the user-agent-fix branch more soon. Things have been hectic to say the least, but I'll get it sorted.

It isn't fun coming up with a way to distinguish and show the default user-agent(s) vs. overrides in some kind of sane way.

**Comment by zanechua** [comment]
I'm assuming this issue is linked with #159 ? Or is this a separate bug altogether.

Trying in the latest nightly release (fa8d5f9c0a56d493e9524eb1a4c920add43e2038) and still doesn't work.

**Comment by indeed-a-genius** [comment]
Issue still present in 8871b6c nightly

**Comment by kyds3k** [comment]
Still having this problem. I got it working in Ferdi by changing my user agent, but doesn't seem to be working here.

**Comment by TheGoddessInari** [comment]
Should be "alright" with 298af38.
Same problems as GMail, though. I could probably use help figuring out how the links are getting mangled/mishandled.

**Comment by TheGoddessInari** [comment]
This should be fixed with 4508c9e.

**Comment by jefaokpta** [comment]
Tnx for share @TheGoddessInari.
I add your code from commit 4508c9e in hangouts advanced settings and it works!
