### ISSUE TITLE
Can't login on Gmail (GSuite): This browser or app may not be secure.

### ISSUE THREAD

**Issue by frankhommers** [TheGoddessInari/hamsket#159]
I am getting this when I add a new GMail (GSuite) account and try to login:

![image](https://user-images.githubusercontent.com/7355878/71720903-821ea180-2e23-11ea-985f-b5a904c188da.png)

**Comment by Anzuul** [comment]
I had the same problem. switching to the `useragent-fix` branch and using Firefox's user agent for Gmail fixed it for me. #126

**Comment by globdug** [comment]
I have same problem but it is strange, because I added 3 Gmail accounts. Two of them worked, the third account give me this error... Hope this will be fixed soon.

**Comment by globdug** [comment]
If can be usefull, I have the same problem with the same account also on Franz and Ferdi. :|

**Comment by alvarobrey** [comment]
As outlined [in this Ferdi issue](https://github.com/getferdi/ferdi/issues/264), there seems to be some whitelisting and/or blacklisting of user-agents in Gmail's side. The ideal fix here would be a new feature that would let the user set a custom user-agent per service.

**Comment by TheGoddessInari** [comment]
I should get the fix merged today barring unforeseen complications.

If you've already tried to sign in and it fails, goes back to the generic pre-sign-in page, you'll need to remake the GMail instance or clear the instance data.

**Comment by TheGoddessInari** [comment]
This should be fixed in f347f53.

Everything else should work as well. Let me know.

**Comment by globdug** [comment]
Oh yes! Now it works!!! THANK YOU! 👍

**Comment by TheGoddessInari** [comment]
If anyone has any ideas on what could be causing the link-handling issues, or if there's a better way to handle this... It'd be preferable that some Chrome user agent worked and could be used for the fallback globally as well, but in all of the research I've done on this issue, the only one I've found to work is the Firefox/Linux one.

**Comment by TheGoddessInari** [comment]
This should be fixed with 4508c9e.

**Comment by HaleTom** [comment]
I'm hitting this issue again now - exactly as show in the initial screenshot.

Is there any way of getting hamsket to browse to here:

https://g.co/allowaccess

???

**Comment by HaleTom** [comment]
I'm guessing that it must work after initial authentication.... is there a way to remove all authentication and start again?
