### ISSUE TITLE
Clicking on notification opens Telegram along with Hamsket

### ISSUE THREAD

**Issue by SinTan1729** [TheGoddessInari/hamsket#160]
### Steps to reproduce

1. Connect to some service (used WhatsApp in my case)
2. Receive any notification
3. Click on it

### Expected behavior

Only Hamsket should open.

### Actual behavior

Telegram opens along with Hamsket

### ENVIRONMENT

> Hamsket: v0.5.20

> OS: Linux Manjaro

> Arch: x64

> BuildVersion: fd21604 (grafted, HEAD, origin/rambox-0.5) Mon, 21 Oct 2019 06:55:30 -0700

> Does this happen upstream: unknown

**Comment by TheGoddessInari** [comment]
Could this be a misconfiguration in the local environment, or a Telegram bug? Both use Electron, but Hamsket shouldn't be trying to deal with any other apps.

Telegram uses many 'interesting' techniques, but realistically I have no idea what it's trying to do here.

**Comment by SinTan1729** [comment]
I'm not sure how, but seems to have been fied.
