### ISSUE TITLE
[Request] Option for "Icon Only" in tab bar

### ISSUE THREAD

**Issue by scrthq** [TheGoddessInari/hamsket#161]
Thank you for continuing OSS development on this client, so awesome!!! Using it a bit and I've found that having a decent amount of services leads to inevitable scrolling or shortening the service name down to something tiny (e.g. "H" for Hangouts, etc). I've resorted to just removing the Name from each service's configuration to mimic this, but it would be great to still have the name in the connections list while being able to choose to display only the icon. Here's what it looks like for me with the tab bar on the left and all service names cleared out:

![image](https://user-images.githubusercontent.com/12724445/71850353-b1d6df00-3099-11ea-916c-0616d22a7ccb.png)

But doing that makes the Enabled Services section a bit of a mystery if you have multiple instances of the same service:

![image](https://user-images.githubusercontent.com/12724445/71850423-e054ba00-3099-11ea-8a13-e84807c7a31d.png)

**Comment by SyntaxErrol** [comment]
You can do this per service. A global option would be faster but this is certainly better than deleting the actual name.
![image](https://user-images.githubusercontent.com/3283914/72051860-b505e100-32cc-11ea-9c8b-e22f26414820.png)

**Comment by scrthq** [comment]
Ahhhh, thank you! That should cover me, I appreciate it!! Totally missed that option before =]
