### ISSUE TITLE
Impossible to remove a service

### ISSUE THREAD

**Issue by schnittchen** [TheGoddessInari/hamsket#166]
I just tried to remove a trello board (custom integration, but it's stuck on the "Removing\nPlease wait until we clear all." pop-up.

If I do anything else (like trying to find out the version number) I might not be able to provide further information for debugging this issue... But I cannot wait forever.

Can I just quit Hamsket now and remove some directory manually to continue?

**Comment by schnittchen** [comment]
Quitting Hamsket does not help, the service stays.

**Comment by schnittchen** [comment]
Removing a partition's directory does not help, it reappears after launch. Current workaround is to disable a service.

**Comment by schnittchen** [comment]
I just tried with the current nightly release, which contains a5e13d5, and part of the problem prevails.

Services can be removed, but the overlay with the spin bar does not go away.

**Comment by TheGoddessInari** [comment]
I've been trying to track down the logic that could allow this to keep occurring, but I'm not finding it. I'll try again to make sure it actually gets closed in a5ec2ca. That's the correct documented thing to do according to the API. If it persists, I'll need to rework the actual calls here, so please let me know.

**Comment by schnittchen** [comment]
Just tried the current nightly. The dialog box still does not close.

**Comment by DrZingo** [comment]
I also have this issue on nightly.
My workaround is:
1. Close hamsket
2. pkill hamsket (kill all hanging threads)
3. cd ~/.config/Hamsket/Partitions
4. rm -r <the_folder_you_want_removed>
5. Restart hamsket

**Comment by TheGoddessInari** [comment]
I think I need further information about the actual behavior.

Has this been any particular services? I've tried many of them and with changes I wasn't having any further problems adding/removing on Windows.

And which OS?  Has this just been happening on Linux? I know I need to check there,

The relevant code is around here https://github.com/TheGoddessInari/hamsket/blob/49c8d2db1d143999b0d5b15baedf39776b220553/app/view/main/MainController.js#L157.

The main thing I **could** see happening is if one of the three calls never succeeds or fails but just hangs, so the finally block also never gets called. This seems like it'd be yet another Electron bug unless I'm just missing some really obvious logic bug.

If this occurs on disabled services, 49c8d2db1d143999b0d5b15baedf39776b220553 should fix it, speaking of logic bugs, but would have no effect on enabled ones being removed.

**Comment by TheGoddessInari** [comment]
d55af40 should fix this. It uses the same style as upstream. If this doesn't fix it, it's likely an Electron bug.

I tested on Linux for this one.

**Comment by DrZingo** [comment]
I tested f675bf2. Still stuck on pop-up when removing a disabled service. But if I enabled the service I could remove it. The folder was still there in .config/Hamsket/Partitions though.

**Comment by TheGoddessInari** [comment]
It's getting an exception in the disabled case,
```
The WebView must be attached to the DOM and the dom-ready event emitted before this method can be called.
```
, because any time something is enabled like that, it should wait until the `dom-ready` event has fired on the webview.

I think I'll try to reengineer this to avoid the use of the WebContents as much as possible, since we should be able to derive the session from the partition data per tab. That should keep it from having to reload the tab altogether just to delete the data, if I'm understanding it right. We'll find out.

**Comment by TheGoddessInari** [comment]
This should finally be solved, as there's no attempt to race the service going online just to kill it.

If there's any problem, it should pop up a dialog box, in addition to logging to the developer console.

If there are **any** more problems, please examine the developer console (ctrl+shift+i by default) for the most recent error/exception stack.

**Comment by ikenichiro** [comment]
This fixed the issue for me. Thanks!

**Comment by schnittchen** [comment]
This is still not removing the subdirectories below `Partitions`.
