### ISSUE TITLE
Per-service Dev Tools won't open

### ISSUE THREAD

**Issue by JakobStruye** [TheGoddessInari/hamsket#167]
### Steps to reproduce

1. Right-click any service tab
2. "Toggle developer tools"

### Expected behavior
The Developer Tools window to open on the right

### Actual behavior
Nothing happens, but the Hamsket-wide dev tools reveals:
```
Uncaught TypeError: Cannot read property 'record' of undefined
    at ctor.toggleDevTools (app.js:5439)
    at Object.callback (app.js:182)
    at ctor.onClick (app.js:4875)
    at ctor.onClick (app.js:4903)
    at ctor.fire (app.js:455)
    at ctor.fire (app.js:740)
    at ctor.publish (app.js:739)
    at ctor.doDelegatedEvent (app.js:741)
    at ctor.onDelegatedEvent (app.js:740)
    at slice$jscomp$1 (app.js:140)
```
I know it worked at some point. I can look into it further later, but maybe someone already knows what's going on.

### ENVIRONMENT

Manjaro Linux, latest build (ac49485).

**Comment by JakobStruye** [comment]
For some reason https://github.com/TheGoddessInari/hamsket/blob/ac49485445396581aeea693610b2e09d83f48903/app/ux/WebView.js#L681 is replaced by ```(void 0)``` in the minified app.js file. I have no why it happens, and it works fine for the similar methods just above it. Manually replacing ```(void 0)``` with ```this``` fixes it, until Hamsket is restarted.

**Comment by TheGoddessInari** [comment]
I'll try replacing this with the updated Sencha CMD and compiler on the build server. Starting with the `20200210.2` that contains Sencha CMD `7.1.0.15` that will finish soon, I'm seeing this as resolved locally. Let me know if it still badly optimizes.
