### ISSUE TITLE
Services not loading until activated manually

### ISSUE THREAD

**Issue by TheGoddessInari** [TheGoddessInari/hamsket#171]
Not sure why/how this is occurring.

I ran into this while working on other code.

This is definitely happening on Windows. I'd like other data points from people.

I've tried rolling back and disabling multiple things but I'm still seeing this.

**Comment by LiBOSS-CZ** [comment]
I am not sure it is related but for me services not loading if I do not have internet connection during startup of Hamsket. Even after the internet connection is working, Hamsket did not reconnect automatically.
If services was normally connected after start then reconnecting is working properly.

**Comment by TheGoddessInari** [comment]
This seems fixed with electron 9.1.x at least.
