### ISSUE TITLE
[macOS] Skype needs a different user agent

### ISSUE THREAD

**Issue by username02** [TheGoddessInari/hamsket#178]
Hi. And first of all thank you very much for this project.
It's amazing :)

Anyway, this:
_Version: 0.6.0
Platform: darwin (x64)
Electron: 8.0.1
Chromium: 80.0.3987.86
Node: 12.13.0
BuildVersion: 37d2be1 (grafted, HEAD, tag: nightly, origin/master) Mon, 24 Feb 2020 10:13:07 -0800_
is the last build making Skype usable to me.

### Steps to reproduce

1. Download a newer nightly version (March 4th or 10th)
2. Skype-tab will appear and you'll be logged in too but you'll be unable to use it since there will be written that Skype isn't disposable for this kind of platform
3. [using february's build Skype become usable again even with a bottom line containing a "Certification Warning"]

### ENVIRONMENT

> Hamsket: v0.6.0

> OS: MacOsMojave 10.14.6

**Comment by TheGoddessInari** [comment]
Go to a google search that says "what is my user agent" on Chrome for MacOS, please, then put the same URL into a custom service on Hamsket, and post the two user agent strings, please.

I likely missed something when creating the manual strings or it behaves in a slightly unexpected way.

**Comment by username02** [comment]
I'm sorry I haven't tried this earlier, before posting the issue :\

Anyway, there was no need to set up a new custom service since pasting this:

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36

in Skype > Options > Advanced > User Agent > Custom User Agent

Skype finally worked again!

**Comment by TheGoddessInari** [comment]
It's alright. I was asking about the difference between the two strings because I might've missed something else or the API output (like OS version) might be surprising or need a special case.

**Comment by username02** [comment]
Sorry as I am... ehm, quite tech-ignorant... So, would you be so kind to tell me how/where exactly could I find the Hamsket user agent string?

**Comment by TheGoddessInari** [comment]
Make a custom service, point it at <https://www.google.com/search?q=what+is+my+user+agent>.

**Comment by username02** [comment]
Ok, Hamsket u.a. is actually:
Mozilla/5.0 (Intel Mac OS X 18.7.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.141 Safari/537.36

(That makes sense: somehow agrees with the no-supported-platform message because, as far as I know, a OsX 18.something doesn't exist yet and latest version should be 10.15.something)

**Comment by TheGoddessInari** [comment]
18.7.0 is the kernel version of Mojave. This is what I mean about surprising output, though. Argh. 🦊

**Comment by TheGoddessInari** [comment]
It's probably the lack of `Macintosh;` at the start, plus maybe dots in the version field. Try 8871b6c and see if that helps.

**Comment by TheGoddessInari** [comment]
Realistically, it should. User agent sniffing in general is daft, but as far as I can tell, aside from running actual commands on the system, there's no way to get the OS release version from just Electron on MacOS, because the equivalent function call of `uname -r` returns a different version.

**Comment by username02** [comment]
Thanks for all the explanations!

So, 8871b6c works perfectly! Thank you!
