### ISSUE TITLE
Hamsket Icon disapears from top bar after screen locked

### ISSUE THREAD

**Issue by sgay** [TheGoddessInari/hamsket#179]
### Steps to reproduce

1. Open hamsket
2. Lock system (via sleep or super+L)
3. Unlock screen

### Expected behavior

When unlocking, it is expected that the hamsket icon persists in the top bar.

### Actual behavior

Hamsket Icon disappears.

This has only begun in build 1588c5e. Other programs do not have the same issue (i.e. skypeforlinux) so I have deduced it is a change with Hamsket.

### ENVIRONMENT

> Hamsket: v0.6.0

> OS: Ubuntu 18.04.4

> Arch: x64

> BuildVersion: 1588c5e

> Does this happen upstream: unknown

**Comment by TheGoddessInari** [comment]
The spellcheck would have nothing to do with it. This is on GNOME, I take it?
Are you using the AppImage?

**Comment by sgay** [comment]
Yes, this is on GNOME with a .deb install. Quite possibly upstream, which I hadn't considered but makes sense considering it's been some time since I updated. Thanks for the help.
