### ISSUE TITLE
[GMAIL] Can't add account. Clicking "Sign In" just opens the page in the web browser.

### ISSUE THREAD

**Issue by SquareBottle** [TheGoddessInari/hamsket#189]
![Screen Shot 2020-04-05 at 5 07 09 PM](https://user-images.githubusercontent.com/60196027/78510102-e1f95100-7760-11ea-8bce-23edbe34bde1.png)

### Steps to reproduce

1. Try to add a Gmail account in Hamsket.
2. Go to the Gmail account in Hamsket.
3. Observe the homepage of the Gmail service.
4. Click "Sign in" in the upper right corner of the page.
5. Observe that the Sign In page loads in your regular web browser.
6. Switch to the Sign In page in your browser and sign in.
7. Observe that you are now signed into Gmail in your browser, not Hamsket.

### Expected behavior

1. Try to add Gmail account in Hamsket.
2. Go to the Gmail account in Hamsket.
3. Observe the Sign In page in Hamsekt.
4. Sign In.
5. Done.

### Actual behavior

It just opens in my browser, and if I continue the sign in process there then I just get signed into Gmail in my browser.

### ENVIRONMENT

> Hamsket: v0.6.0

> OS: macOS High Sierra 10.13.3

> Arch: x64

> BuildVersion: 9ac6425

> Does this happen upstream: unknown

**Comment by TheGoddessInari** [comment]
Again, Google changed their services to reject electron-based apps. Changing the user agent to Firefox 'works' around the hard block, but if you're getting the "sign in" page on GMail instead of an email prompt, you have to clear the app data for the tab and reload.

**Comment by SquareBottle** [comment]
Thank you. I deleted and re-added them, and it works great.

**Comment by diego-treitos** [comment]
@TheGoddessInari And how do you change the user agent in hamsket?

**Comment by TheGoddessInari** [comment]
The user agent tab under advanced for each service.

**Comment by TheGoddessInari** [comment]
This could be fixed with 4508c9e.
If the "sign in" page shows up again and acts funny, let me know.

**Comment by wefalltomorrow** [comment]
![image](https://user-images.githubusercontent.com/45746576/90247360-c1ad7180-de79-11ea-8cad-a5c5c48165c0.png)

Get this message no matter how many times I refresh.
