### ISSUE TITLE
Google Voice - fails to authenticate

### ISSUE THREAD

**Issue by bshensky** [TheGoddessInari/hamsket#195]
### Steps to reproduce

1. Add Google Voice addon
2. Attempt login with Google username

### Expected behavior

Expected login successful, and route to Google Voice.

### Actual behavior

Rather than see expected password prompt, get message that says "Couldn't sign you in
This browser or app may not be secure. (Learn more) Try using a different browser. If you’re already using a supported browser, you can refresh your screen and try again to sign in."

Repeat above, even after having changed User-Agent to match local Chrome instance: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.162 Safari/537.36".  Tried a multitude of other "Override OS" values as well.  Still no dice

### ENVIRONMENT

Hamsket: v0.6.0
OS: Windows 10
Arch: x64
BuildVersion: 1911 OR 2004
Does this happen upstream: unknown

Captures of Hamsket and Native Chrome Request Headers:

HAMSKET
:authority: accounts.google.com
:method: GET
:path: /ServiceLogin?service=grandcentral&passive=1209600&continue=https://voice.google.com/signup&followup=https://voice.google.com/signup
:scheme: https
accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
accept-encoding: gzip, deflate, br
accept-language: en-US
cookie: NID=202=fDkr5YXKfH_KDkGkqb9lknlrQQVDRSCkE8m99iEBfsfLUs5wEAB08TeNG59oZ3ks5IOrOH55sSa7Fm-FuRafZN_3XMgjVvaJbwCBKavOb4NwCw3f7tYd-_issEvpiPGajQMIFDihiaZFo_xtPCA04-9y2o1E07ysom3bkzOLJf8; GAPS=1:L3X-Yz9Lb8qR5WuZGmZijcGVif6Y5A:2fN71NBKnsd7ExQ4
referer: https://voice.google.com/about
sec-fetch-dest: document
sec-fetch-mode: navigate
sec-fetch-site: same-site
sec-fetch-user: ?1
upgrade-insecure-requests: 1
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.162 Safari/537.36

CHROME
:authority: accounts.google.com
:method: GET
:path: /ServiceLogin?service=grandcentral&passive=1209600&continue=https://voice.google.com/signup&followup=https://voice.google.com/signup
:scheme: https
accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
accept-encoding: gzip, deflate, br
accept-language: en-US,en;q=0.9,es;q=0.8
cache-control: no-cache
cookie: SMSV=ADHTe-CpqHQ0AZbzp9hJLQYlfxU46CA_JEVkrSYhXBb7XIryCJB81WWabYmiWog9l3HX5Ko1BFH4-32dtOO50d_kK0rlJdb5kSwqq-KRnjW7XYv84Z99PXtY_xoivDAX4NtAoCLorG2nrzP7oMwg61M5qmfauQNkuBskAL6shZ84DAD61bSYHD5IAjEZVkZJLeRL_JSR3l4Le64vJC1vCH_tAyKIkgZ8mA; ACCOUNT_CHOOSER=AFx_qI66zm3ssYzxK5fGEeMWF2F4i3C8NuLqhCGx7F1u5z3I7flDpla8TT5aknX7RqzhJoixZFBdW03LBJeXd-C2nvUsYe_9mtGWPSe8apc6TOWXtdSAiiOcIpO1OiiqWtakD-Cyqa8KFe_o2QIbPp0Iug9_DgKI8B9BrgeALhsB029GJTtiOfawq1yL78DIxCQUZ1YyDPdqj-1SnSe_n40Gg4F6noVk2bQvBRBSBUWv_E2_qEExe7fGo3y53x9mFlAlOtGZwCMhx3slCZSDZq6UphXTNlhKw9k_AheHk31dWoKhSsjdpvEQRSmJJNgETcbjYF1CRF6qVWaqO4DDNDb_35cIBtM51ey_xCCk17_XYHZh8ZQd2LtMadWoTs0voeOFR_FAJ6wmpZR-2anoA6Nog0m2-wmrsGjMSTqTvDl6Kql5x-L4xHRx_HbEw5250jrI9mRybq4cnWqNvmsf6UyqNmJ6knVU9OHzypp3F6aNDA50SEY56YHykoS2Z2cmNLYw-WLP7yvdRD5dvqNYMpZdX6m3Z69wdn4Iq4-Nrd6oKiazccOuX5NfBvly9Kx7X_0EB_KGrwWQ; LSOLH=_SVI_Ch8wOWR4ZllMZmQtc1FZSlNaRmRSbnUzUlA3a2JvQUJjEMO8waqLt-cCGAQiP01BRURIZl9xdWFRU0NBTWxkVHdKc2V0VlFxWTlkcDN1YUxsdlB0XzZVVGRNZ0FHa2VRTTExeUlxNm5SMXZHMA_:26346540:88c2; SEARCH_SAMESITE=CgQIiY8B; OGP=-19016257:; OGPC=19016664-4:19016257-1:19008563-5:; ANID=AHWqTUmdczzYO7dt3JIfbYu7YzAQmRC9dDgQoJHWG-XXnXCKGfk7mlMNVFDTd-qV; S=billing-ui-v3=CPxsa3sanQKRiZE8eG_3lnT-wd6Fw0C2:billing-ui-v3-efe=CPxsa3sanQKRiZE8eG_3lnT-wd6Fw0C2; 1P_JAR=2020-4-20-14; NID=202=PS6_CPFVWTJNxz2LOjBUttusGq_7cosLeyaHF1vRERdA_dNszeeEUIXTpiSzUFt-AvU5eFMz1RJEtJOV0FTmyTlUNrbs41OippiZEvLM2Sq4Y-4FlfEfqy5fr2qEjSGJX0Toj2llGwEQa7pbAYSIf550fOa849EdDe2dmYrnDdzpjq0oNnPNDgkw3_ixNhFOkW5zXXe0615V8Z4Q6Ajz; GAPS=1:yN7dTCC69JbBvxKvTrgywSo4nrcdso1bAGlr35uhdlLaEDVcD_SirtirnJAxg0wgQuhJCMIQn6mX7VcRDwBKpPWNHaJqfVEv3AFTGUcvE21PUuqOxFfaq5tQ4oaTyQ:fqYx2mX293zB1-tO
pragma: no-cache
referer: https://voice.google.com/about
sec-fetch-dest: document
sec-fetch-mode: navigate
sec-fetch-site: same-site
sec-fetch-user: ?1
upgrade-insecure-requests: 1
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.162 Safari/537.36
x-chrome-connected: mode=0,enable_account_consistency=false,consistency_enabled_by_default=false
x-chrome-id-consistency-request: version=1,client_id=77185425430.apps.googleusercontent.com,device_id=ce369d85-31e2-4837-95b2-b3ee67e96999,sync_account_id=117116667871689390038,signin_mode=all_accounts,signout_mode=show_confirmation

--fin--

**Comment by TheGoddessInari** [comment]
Generally need the Hamsket version as reported in the template/about, not your cookies.

It works out of the box on 298af38 and newer.

Other than finding a version of Chrome that works with this and the Fallback User Agent, it'll have the link problems and other drawbacks for now.

**Comment by TheGoddessInari** [comment]
This should work with 4508c9e.
