### ISSUE TITLE
[WhatsApp] Unread message notification + counter

### ISSUE THREAD

**Issue by LiBOSS-CZ** [TheGoddessInari/hamsket#199]
### Steps to reproduce

1. Recieve new message in Whatsapp

### Expected behavior

Icon in tray goes red and tab show number of unread message.

### Actual behavior

Nothing happened.

### ENVIRONMENT

> Hamsket: v0.6.0

> OS: Windows 10 Pro x64 CZ

> Arch: x64

> BuildVersion: 63ef955

> Does this happen upstream: unknown

**Comment by TheGoddessInari** [comment]
This should be fixed in bb9df29. Let me know if not.

**Comment by LiBOSS-CZ** [comment]
Yes, working int the latest build d78a4ea

**Comment by LiBOSS-CZ** [comment]
And is back again:-( even with the latest build 6989a23

**Comment by TheGoddessInari** [comment]
**Should** be fixed in 9e1abaf.

**Comment by LiBOSS-CZ** [comment]
Seems to be working. Nice job.

**Comment by LiBOSS-CZ** [comment]
Again not working :-(

**Comment by flying-sheep** [comment]
This needs to be fixed for real, not by adapting some randomly generated CSS class whenever they deploy anew.

The style of the badge class is this:

```js
._38M1B{
  display:inline-block;
  min-width:.9em;
  min-height:1em;
  font-size:12px;
  font-weight:600;
  line-height:1em;
  color:var(--unread-marker-text);
  vertical-align:top}
html[dir] ._38M1B{
  padding:.3em .4em .4em;
  text-align:center;
  background-color:var(--unread-marker-background);
  border-radius:1.1em
}
html[dir] .vc2I1{
  background-color:var(--unread-marker-background-muted)
}
.os-mac ._38M1B{
min-width:.8em;font-weight:500
}
html[dir] .os-mac ._38M1B{
  padding:.3em .4em
}
```

Therefore we can find the class using:

```js
const className = Array.from(document.styleSheets)
  .flatMap(s => Array.from(s.cssRules))
  .filter(r => r instanceof CSSStyleRule)
  .find(({style}) => style.color === 'var(--unread-marker-text)')
  .selectorText.split('.').reverse()[0]
```

(I went for `split → reverse → [0]` instead of `substring(1)` in case they add some selector in front in the future)

**Comment by LiBOSS-CZ** [comment]
Any news about Whatsapp unread message fix? It will be highly appreciated.
