### ISSUE TITLE
Linux: Links from Gmail don't work

### ISSUE THREAD

**Issue by aljinovic** [TheGoddessInari/hamsket#204]
Links from Gmail open a white popup window with title "_blank".

Same for both Arch Linux packages:
- https://aur.archlinux.org/packages/hamsket-nightly-bin/
- https://aur.archlinux.org/packages/hamsket-git/

	
	-
	> Hamsket 0.6.0
	> Electron 8.2.5
	> linux x64 5.6.13-arch1-1
	> d78a4ea  (HEAD -> master, tag: nightly, origin/master, origin/HEAD) Sat, 2 May 2020 16:38:47 -0700

**Comment by wefalltomorrow** [comment]
https://github.com/TheGoddessInari/hamsket/issues/176

**Comment by TheGoddessInari** [comment]
This should be fixed with 4508c9e.

**Comment by TheGoddessInari** [comment]
This should be fixed with the cumulative Google Login changes, currently with cd01cec.
