### ISSUE TITLE
Any way to add more Ctrl + <number> shortcuts?

### ISSUE THREAD

**Issue by ngoonee** [TheGoddessInari/hamsket#210]
I have 5 services currently (that are active, have another half a dozen inactive), but only the first four are directly accessible (Ctrl+1, Ctrl+2 etc.). Ctrl+5 doesn't work, is there an easy way to enable it? I've seen some code that you've mentioned in related issues but don't know if that's configurable.

I'm using the nightly if that makes a difference.

**Comment by TheGoddessInari** [comment]
Would you be able to tell me the Hamsket build and OS version?

```javascript
						{
							label: `Goto Tab 5`,
							accelerator: 'CmdOrCtrl+5',
							click() {
								sendAction('focusTab', 5);
							}
						},
```
is the relevant code, so the code exists, and it works on my Windows development machine, also worked on Linux w/ KDE last I checked.

**Comment by ngoonee** [comment]
Downloaded from https://github.com/TheGoddessInari/hamsket/releases/download/nightly/hamsket-0.6.0.tar.gz

I'm using Arch Linux, and I'm installing using the AUR package (all it does is the following, where srcdir/pkgdir are directories for staging and putting the files) so it's just extracting the tar to /opt.

    cp -R ${srcdir}/hamsket-${pkgver}/* ${pkgdir}/opt/${_pkgname}/
    ln -rs ${pkgdir}/opt/${_pkgname}/hamsket ${pkgdir}/usr/bin/hamsket
    chmod 4755 ${pkgdir}/opt/${_pkgname}/chrome-sandbox

**Comment by ngoonee** [comment]
Ah it may be something specific to my laptop/system.... tried adding one more service, and Ctrl+6 works! Sorry, my bad.
