### ISSUE TITLE
Riot is now Element

### ISSUE THREAD

**Issue by pschiffe** [TheGoddessInari/hamsket#216]
Hello; Riot is changing it's brand to Element, which involves changing the domains:

> You can still access your old Riot client at your usual URL hosted at riot.im (e.g.your.riot.im), but this will sunset soon.
> 
> Your new Element instance is ready for you to sign in at the same subdomain on element.io (e.g. your.element.io).

https://element.io/previously-riot

peter

**Comment by TheGoddessInari** [comment]
I'm still updating the unread JS for this.

If anyone feels like helping, it'd be appreciated.

**Comment by pschiffe** [comment]
Hey, thanks for your awesome work! I would love to help, but this is outside of my area :/

**Comment by TheGoddessInari** [comment]
It **should** work with both rooms and person notifications as of 9ab646e, but I didn't find anyone to test with me, so just kinda waited for rooms to blip off.

As well as generic "dot" indirect notifications.

**Comment by pschiffe** [comment]
Hi @TheGoddessInari . I can confirm that the notifications are working in Element for person messages, great job!

But I noticed that the dot indicator and number of messages is not working for slack (in the latest nightly build). I'm not sure if it worked before, or since when it doesn't.

**Comment by pschiffe** [comment]
Reg. the slack - the notification appears after I open the tab with slack, or if it's open I need to scroll a bit, it doesn't appear by itself automatically. sorry for writing it here -_-

**Comment by TheGoddessInari** [comment]
I think there was a slack issue somewhere.

Right now, I get the indirect notices fine, but I don't get enough direct messages or pings to often test Slack.
