### ISSUE TITLE
Gmail unable to sign-in

### ISSUE THREAD

**Issue by wefalltomorrow** [TheGoddessInari/hamsket#219]
Using the latest nightly on Windows 10 x64 and every time I try and sign-in to Gmail it results in this error, no matter how many times I refresh or remove and then re-add Gmail to Hamsket.

![image](https://user-images.githubusercontent.com/45746576/90849341-65cf7500-e3b2-11ea-9906-36b4f49ee2de.png)

On an unrelated note, will the ability to have multiple Google accounts signed into Gmail in Hmasket ever be added?

Cheers.

**Comment by chwba** [comment]
@louisabraham  Yes, I tried to use the newest chrome.

**Comment by TheGoddessInari** [comment]
This should be fixed with cd01cec.

Sorry for the delay. Life happened.

Let me know if there are more problems or bugs here.

**Comment by wefalltomorrow** [comment]
[**@TheGoddessInari**](https://github.com/TheGoddessInari) commented on [Sep 3, 2020, 2:31 AM GMT+10](https://github.com/TheGoddessInari/hamsket/issues/219#issuecomment-685852347 "2020-09-02T16:31:03Z - Replied by Github Reply Comments"):
> This should be fixed with [cd01cec](https://github.com/TheGoddessInari/hamsket/commit/cd01cec016adf843c448c0e82f0bdbb2e0a8880a).
> 
> Sorry for the delay. Life happened.
> 
> Let me know if there are more problems or bugs here.

Thanks! Works great :)
