### ISSUE TITLE
Slack icon code appearing

### ISSUE THREAD

**Issue by jsangeorzan** [TheGoddessInari/hamsket#225]
Sorry doing my best here its my first submitting a bug!
![Screenshot_1](https://user-images.githubusercontent.com/15372288/94087911-f0095f80-fddc-11ea-8ae6-2bcd5c79c87c.png)

Note this happens on all my systems I have Hamsket on and it seems to 100% be relate to the 2 instances of Slack I have configured. 

### Steps to reproduce

1. Just leaving slack connected seems to have it randomly occur
2. Have tried deleting and re-adding the accounts, it seems to be fine for a few days then occurs again randomly.
3. 

### Expected behavior

Window should not fall out of frame and show code.

### Actual behavior

Code shows where slack widow should be and pushes all the windows to the right.

### ENVIRONMENT

> Hamsket: v0.60

> OS: Win 10 Pro

> Arch: x64

> BuildVersion:

> Does this happen upstream: yes, no, unknown, or N/A

**Comment by SyntaxErrol** [comment]
I was just gonna post this too. Mine looks like this:
![image](https://user-images.githubusercontent.com/3283914/94107641-92116200-fe46-11ea-9ba6-a18cdc36e6ae.png)

Note you can temporarily cure this by editing Slacks's service settings. Simply opening the settings and hitting (the mislabeled) [Edit Slack] button makes the \<img\> tag go away.

**Comment by jsangeorzan** [comment]
I align all of my stuff left, so I sadly I can't easily refresh.  Haha, but nice to know you can easily edit it and make it go away.

**Comment by TheGoddessInari** [comment]
I see this too. I'll investigate what's causing this to crop up (periodically) ASAP.

**Comment by aravindhp** [comment]
I saw this issue again today even after the fix went in.

>Version: 0.6.0
Platform: linux (x64)
Electron: 10.1.4
Chromium: 85.0.4183.121
Node: 12.16.3
BuildVersion: b42bfb8 (grafted, HEAD, tag: nightly, origin/master) Mon, 2 Nov 2020 20:09:16 -0800

**Comment by flying-sheep** [comment]
I’m also seeing this …

**Comment by TheGoddessInari** [comment]
I've finally narrowed this down. The only reason it's visible is that we escape the user-provided string. This "should" be the service's **name**, and not the existing title.

This was inherited from Rambox, which has the same issue (but doesn't escape anything). Rambox sets the title, then reads back the title, so any subsequent changes to title stack more than one icon(!) in the title, which is normally invisible. I'm validating a change to make sure this sets the title (and logs errors reasonably) instead of just blindly stacking an unlimited number of icons into the title.

**Comment by flying-sheep** [comment]
Beautiful, thank you!

**Comment by flying-sheep** [comment]
Could you please release a new version with this? It’s a great bug to no longer encounter!

**Comment by borospeti** [comment]
I have built hamsket from sources with the patch from commit 3bad65c and tested it a for a couple of weeks. (I have three slack services online most of the time). I am not seeing the icon turning into html code anymore (it happened fairly often before). However, the icons still get duplicated sometimes, with a tiny copy of the icon in the bottom right corner of the normal icon. This seems to happen with all three services at the same time. (All of them are using custom icons.)
Simply opening the Edit dialog for the service, and clicking "Edit <SERVICE>" fixes the icon, and then it stays ok for several days (or longer). I haven't found a way to trigger the issue. This icons are always ok after Hamsket is restarted.
