### ISSUE TITLE
Unable to log into Google services

### ISSUE THREAD

**Issue by JaxNekomancer** [TheGoddessInari/hamsket#229]
When I try to add Google services (Gmail, Hangouts, Google Voice) I get the following message:
Couldn't sign you in
This browser or app may not be secure. Learn more
Try using a different browser. If you’re already using a supported browser, you can refresh your screen and try again to sign in.

	
	-
	> Hamsket 0.6.0
	> Electron 8.0.0
	> win32 x64 10.0.19041
	> ac49485  (grafted, HEAD, origin/master) Tue, 4 Feb 2020 16:13:12 -0800

**Comment by reggermont** [comment]
Please update to latest Hamsket version, I personally don't have this issue

**Comment by splatch** [comment]
I can confirm that update to nightly build solved problem.

**Comment by JaxNekomancer** [comment]
When I try to update, it tells me I have the latest version.
*Version:* 0.6.0
*Platform:* win32 (x64)
*Electron:* 8.0.0
*Chromium:* 80.0.3987.86
*Node:* 12.13.0
*BuildVersion:* ac49485 (grafted, HEAD, origin/master) Tue, 4 Feb 2020
16:13:12 -0800
____________________________________________
When a man loves cats, I am his friend and comrade, without further
introduction.
-- Mark Twain

Ezra B. Riner
Jacksonville, FL 32216
ezra.riner@gmail.com
(904) 567-8284

**Comment by reggermont** [comment]
`*BuildVersion:* ac49485 (grafted, HEAD, origin/master) Tue, 4 Feb 2020`
I can assure you this is not the latest version ^^

https://github.com/TheGoddessInari/hamsket/releases/tag/nightly
