### ISSUE TITLE
Rename a service

### ISSUE THREAD

**Issue by PapsOu** [TheGoddessInari/hamsket#230]
Is there a way to rename an existing Service ?

### ENVIRONMENT

```
Version: 0.6.0
Plateforme: linux (x64)
Electron: 8.2.3
Chromium: 80.0.3987.163
Node: 12.13.0
BuildVersion: d78a4ea (HEAD -> master, tag: nightly, origin/master, origin/HEAD) Sat, 2 May 2020 16:38:47 -0700
```

**Comment by LiBOSS-CZ** [comment]
Yes,
in the main window, there is a list with enabled services. Each service has three icons (mute, settings and delete). If you select the settings, you can rename service.

**Comment by PapsOu** [comment]
Ok, so easy to find, my bad :+1:

**Comment by TheGoddessInari** [comment]
Just glad you were able to get some help and figure this out. ^^;
