### ISSUE TITLE
Discord reset each Rambox reboot

### ISSUE THREAD

**Issue by Crash95460** [TheGoddessInari/hamsket#231]
-
	> Rambox 0.5.20
	> Electron 5.0.11
	> win32 x64 10.0.19041
	> fd21604  (grafted, HEAD, origin/rambox-0.5) Mon, 21 Oct 2019 06:55:30 -0700

**Comment by TheGoddessInari** [comment]
Please try nightly if you haven't yet. I'm hoping to get a new release out "soon", but there's a major blocker (due to Electron) on Skype calls, and possibly Slack notifications.

**Comment by TheGoddessInari** [comment]
The main point of the 0.5.x branch was to offer a way to migrate from Rambox (at the time) to Hamsket without losing your services or custom JS, etc. The actual localStorage stuff (so your login) can't be preserved through a backup/restore at this time.

**Comment by TheGoddessInari** [comment]
Never got any response on this and 0.6.x stable has been out.
