### ISSUE TITLE
Ctrl+click opens a new Hamsket Window + the default browser

### ISSUE THREAD

**Issue by necrevistonnezr** [TheGoddessInari/hamsket#232]
### Steps to reproduce

1. Ctrl + click on link in a Hamsket window
2. Link is opened in a new Hamsket Window _and_ the default browser

### Expected behavior

Link is only opened in the default browser

### Actual behavior

Link is opened in a new Hamsket Window _and_ the default browser

### ENVIRONMENT

> Hamsket: 0.6.0

> OS: Windows 10, 64 bit

> Build: 06c8aef (Nightly, 23 October 2020)

**Comment by necrevistonnezr** [comment]
Note: The previous build (https://dev.azure.com/TheGoddessInari/hamsket/_build/results?buildId=230&view=artifacts&type=publishedArtifacts) does not display this behaviour.

**Comment by aljinovic** [comment]
This happens only in Gmail on Linux, for both click and CTRL+click. Links from Slack and Whatsapp work normal.

**Comment by killtux** [comment]
same issue here. even if i click it normally it opens two windows (1x hamsket,  1x default browser). latest nighty.

**Comment by bchooxg** [comment]
Hi i am currently experiencing this issue. Clicking on a link in the gmail tab opens both hamsket window + chrome

**Comment by BozanicJosip** [comment]
Experiencing the same issue that @aljinovic described

**Comment by bchooxg** [comment]
Does anyone have a fix for this issue?

**Comment by itsgaryk** [comment]
I'm experiencing a similar issue and it only happens on Facebook Messenger and LinkedIn

> BuildVersion: fd10375 (grafted, HEAD, tag: 0.6.2, origin/fd1037521df6214a1b6b3751242cfa409c4ac236) Thu, 10 Dec 2020 17:32:22 -0800

**Comment by julientaq** [comment]
Hi there!

Thanks a lot for all the work you’re putting into Hamsket

I have the same issue on osx Catalina, in diverse Mattermost links, even when i don’t use ctrl+click. (Mattermost may open links in a new tab by default).
 
Interrestingly enough, it’s not happening in discord.

```
Version: 0.6.2
Plateforme: darwin (x64)
Electron: 10.1.7
Chromium: 85.0.4183.121
Node: 12.16.3
BuildVersion: fd10375 (grafted, HEAD, tag: 0.6.2, origin/fd1037521df6214a1b6b3751242cfa409c4ac236) Thu, 10 Dec 2020 17:32:22 -0800
```

Thanks!

**Comment by nixsee** [comment]
I have this issue **only in Gmail** on Windows 10 Pro Build 19042, Hamsket v0.6.2

**Comment by bchooxg** [comment]
Is anyone currently working on a fix for this ?

**Comment by arvindgaba** [comment]
Does any have any update on this issue, it is annoying when you click on any link in Gmail.
