### ISSUE TITLE
Adding a 2nd instance of the same service crashing in 0.6.0

### ISSUE THREAD

**Issue by vraravam** [TheGoddessInari/hamsket#238]
### Steps to reproduce

1. Add service Gmail (call it "Work Gmail") and save
2. Add service Gmail (call it "Personal Gmail") and save
3. BOOM

### Expected behavior

The user is able to add more than 1 instance of the same service

### Actual behavior

Adding the 2nd instance of the same service, crashes hamsket

### ENVIRONMENT

> Hamsket: v0.6.0

> OS: Mac OS Big Sur

> Arch: x64

> BuildVersion:

> Does this happen upstream: yes, no, unknown, or N/A

**Comment by LiBOSS-CZ** [comment]
I am using 2 Whatsapp without problems.
Windows 10 x64

**Comment by TheGoddessInari** [comment]
Ping me if you can reproduce this, preferably on Linux or Windows; there's literally no way for me to test on MacOS, and MacOS specific problems that have nothing to do with my code (so crashes especially) are either an Electron or MacOS error that it's highly unlikely for me to be able to directly work around unless it's a specific known issue, and someone's already figured out a workaround.

Otherwise, this'll get closed soon because I have a ton of instances of many diferent services, and 0.6.3 is readying up.

**Comment by vraravam** [comment]
Sorry - since the keyboard shortcuts issue was never fixed, I have moved onto Ferdi - and have also started contributing to it heavily. Wish you all the best in taking this further. Closing the issue now.

**Comment by francwalter** [comment]
> Sorry - since the keyboard shortcuts issue was never fixed, I have moved onto Ferdi - and have also started contributing to it heavily. Wish you all the best in taking this further. Closing the issue now.

Tried Ferdi before, it is not as easy to add some websites to the services. Hamsket is maybe not anymore under development, unfortunately, but came further than Rambok and both better than the Franz-Ferdi Apps, I consider.

**Comment by vraravam** [comment]
@francwalter - I invite you to please download the [latest nightly](https://github.com/getferdi/nightlies/releases) that's for your OS/arch - and try it out. There have been lots of development in the recent past. We have also upgraded to the latest electron (v13.0.0 - as of tonight's nightly build). I am sure you will be pleasantly surprised. And if not, please do help by logging feature requests.

**Comment by francwalter** [comment]
As I remember it was not possible to add any arbitrary website (with remembered login) as new service.
This changed?
This is the killer feature in Rambox / Hamsket, I believe.

**Comment by vraravam** [comment]
Thanks for the specific pointer - I will see what can be done to accomplish this.
