### ISSUE TITLE
0.5.18?: Add spellcheck

### ISSUE THREAD

**Issue by TheGoddessInari** [TheGoddessInari/hamsket#25]
Assuming people want this, we can reasonably do so, at least for English, French, German, and Spanish.

**Comment by TheGoddessInari** [comment]
Like mobile WebView, it appeared this was easily possible, but in testing, despite wiring up a spellchecker according to documentation. This means either:
1. Electron's documentation is wrong and there's just some other way to wire it up. I wired it up according to docs, similar to how other projects do it, and nothing happened. 
2. Electron 2.0.x is interfering with it, similar to how it messes with some other things.
3. ExtJS is somehow interfering.

**Comment by TheGoddessInari** [comment]
Trying an alternate approach today that might work better for spellcheck and context menu. Initial results are promising.

**Comment by HaleTom** [comment]
Thanks for your work on this. Your commitment to this project is outstanding. I hope you continue to receive support.

**Comment by BuildTheRobots** [comment]
Apologies for bumping without contributing anything of value, but I don't suppose there's been an update on the spellcheck feature?

**Comment by prediscover** [comment]
Eager for spellcheck! Noticed some changes in the new release, was there an update?

**Comment by parf78** [comment]
Curious if there's been any update on this? Spellcheck is the only thing holding me back.

**Comment by eliliam** [comment]
I just found this project after looking for some way to get spell check into Rambox, I am considering switching and spell check would be a major part of that for me. I see the ticket is still in the To Do section, has there been any developments with this yet?

**Comment by TheGoddessInari** [comment]
Electron added built-in spellcheck. Expect this soon if it's sane.

**Comment by TheGoddessInari** [comment]
This appears broken upstream even on 8.0.0 for Windows/Linux. Only works on MacOS.

Eg https://user-images.githubusercontent.com/42934634/72342048-6d1ff900-36d4-11ea-9f9b-0650553a6cb7.png

**Comment by eliliam** [comment]
That's great news, is there a quick patch that I can make to enable spell check before it officially is implemented?

**Comment by TheGoddessInari** [comment]
Fixed with electron 8.10 and 1588c5e. Unsurprisingly it was an upstream issue on 8.0.0 that kept it from working on Windows.

**Comment by sgay** [comment]
Hi there,
Thanks very much for this last update, spellcheck is a killer feature. I'm having trouble getting it to work across all my services though- currently I have it working on Messenger and Gmail (although I suspect the latter is the inbuilt gmail one) but not on Whatsapp (web)/LinkedIn messaging. 

Is this to do with how these particular web platforms are constructed and electron not recognising userfields to spellcheck?

One thing that might make your life easier is the [Languagetool](https://languagetool.org/) chromium plugin. I don't know anything about javascript/electron but based on [this but report](https://github.com/electron/electron/issues/19447) (which I found from [a SO thread](https://stackoverflow.com/questions/53341132/how-can-i-add-a-custom-chrome-extension-to-my-electron-app)) it appears chromium extensions could soon be ready to hitch onto electron.

If that's the case, perhaps you could enable a setting to turn install/turn on languagetools and that way the spellcheck will work across all platforms and also include grammer checking (plus a huge language library).

**Comment by BKPepe** [comment]
Am I doing something wrong or spellcheck in Hamsket supports just English?

**Comment by TheGoddessInari** [comment]
I'll figure out a way to get Electron loading the right dictionaries based
on language selected, it just might end up a pain since everything expects
different language abbreviations.

**Comment by leogallego** [comment]
> I'll figure out a way to get Electron loading the right dictionaries based on language selected, it just might end up a pain since everything expects different language abbreviations.

Is there a way to enable the spell check language per tab maybe? 

Usually most of us who are not native English speakers use one language for the interface but have several services in different languages, even if we had the interface in the right language, there would be services were the spell checker wouldn't work.

ps. maybe this should be reopened or made another issue as a feature request?
