### ISSUE TITLE
Popups are opening both on Hamsket and in my browser

### ISSUE THREAD

**Issue by AntoninJcb** [TheGoddessInari/hamsket#255]
### Steps to reproduce

1. Chose an app that has external links, like a mail in Gmail for instance
2. Click on the link

### Expected behavior

The link should raise a popup with its target content.

### Actual behavior

It both raises a popup and loads up in my default browser at the same time.

### ENVIRONMENT

> Hamsket: v0.6.2

> OS: debian bullseye

> Arch: x64

> BuildVersion: Linux 5.10.0-2-amd64 x86_64

> Does this happen upstream: unknown

**Comment by AntoninJcb** [comment]
Ops, looks like there is a similar issue #232 , 
Feel free to close this one if you can confirm they have the same origin

**Comment by nixsee** [comment]
Likewise
