### ISSUE TITLE
glibc 2.34 causes crashing as its breaks sandboxing in electron

### ISSUE THREAD

**Issue by ahjolinna** [TheGoddessInari/hamsket#276]
https://bugs.launchpad.net/ubuntu/+source/glibc/+bug/1944468
https://github.com/microsoft/vscode/issues/132609
https://github.com/microsoft/vscode/issues/133593
https://github.com/electron/electron/pull/31091

Merged for electron 13 : https://github.com/electron/electron/commit/993ecb5bdd5c57024c8718ca6203a8f924d6d574

tmp solution is to run with: `--disable-gpu-sandbox`

**Comment by TheGoddessInari** [comment]
Looks like this should be fixed with 87e9e615.

**Comment by ahjolinna** [comment]
> Looks like this should be fixed with [87e9e61](https://github.com/TheGoddessInari/hamsket/commit/87e9e615654b58ceaaf14f1fad7158c3e0cd854c).

yeah I tested the [Nightly version](https://github.com/TheGoddessInari/hamsket/releases/tag/nightly) and it seems to work just fine so I will be closing this
