### ISSUE TITLE
Outlook Unread Counter updating very sporadically

### ISSUE THREAD

**Issue by nickchomey** [TheGoddessInari/hamsket#281]
As described, the unread counter rarely updates, but it does sometimes. Reloading the service or Hamsket doesnt help.

Version: 0.6.2
Platform: win32 (x64)
Electron: 10.1.7
Chromium: 85.0.4183.121
Node: 12.16.3
BuildVersion: fd10375 (grafted, HEAD, tag: 0.6.2, origin/fd1037521df6214a1b6b3751242cfa409c4ac236) Thu, 10 Dec 2020 17:32:22 -0800

**Comment by TheGoddessInari** [comment]
feceef98 or newer **should** fix this, fwiw.
