### ISSUE TITLE
Google Translate custom service doesn't load anymore.

### ISSUE THREAD

**Issue by nickchomey** [TheGoddessInari/hamsket#282]
### Steps to reproduce

1. Create a new service with https://translate.google.com as the URL
2. Click on tab

### Expected behavior

Ability to use the site

### Actual behavior

Blank white page

### ENVIRONMENT

Version: 0.6.2
Platform: win32 (x64)
Electron: 10.1.7
Chromium: 85.0.4183.121
Node: 12.16.3
BuildVersion: fd10375 (grafted, HEAD, tag: 0.6.2, origin/fd1037521df6214a1b6b3751242cfa409c4ac236) Thu, 10 Dec 2020 17:32:22 -0800

**Comment by TheGoddessInari** [comment]
0.6.2 is quite old, as stabilization for a new version has been quite troublesome.

If a newer build didn't fix it otherwise, 2722614 definitely does.

**Comment by nickchomey** [comment]
@TheGoddessInari as far as I'm aware 0.6.2 was the only release available... Should I install your latest nightly release?
