### ISSUE TITLE
ProtonMail login returning "Invalid character" error

### ISSUE THREAD

**Issue by aravindhp** [TheGoddessInari/hamsket#291]
I am unable to login to ProtonMail using Hamsket. This is working on all other browsers.

### Steps to reproduce

1. Add ProtonMail 
2. Try to login

### Expected behavior

Login should succeed

### Actual behavior

Login returns "Invalid character" message

### ENVIRONMENT

Version: 0.6.3
Platform: linux (x64)
Electron: 16.0.4
Chromium: 96.0.4664.55
Node: 16.9.1
BuildVersion: b99b033 (grafted, HEAD, tag: nightly, origin/b99b033f331565df28128b76109f3a5a72911c30) Tue, 7 Dec 2021 23:54:05 -0800
Does this happen upstream: unknown

**Comment by TheGoddessInari** [comment]
Of course...
Another bizarre upstream issue that isn't getting any traction. 😭 
https://github.com/electron/electron/issues/31018

**Comment by aravindhp** [comment]
@TheGoddessInari any chance of downgrading electron to a version that does not have this issue? Or does that break something else?

**Comment by alien2003** [comment]
Confirmed, would be great to fix it

**Comment by aravindhp** [comment]
> @TheGoddessInari any chance of downgrading electron to a version that does not have this issue? Or does that break something else?

@TheGoddessInari any thoughts on doing this?

**Comment by aravindhp** [comment]
Thank you fixing this @TheGoddessInari

**Comment by TheGoddessInari** [comment]
I'm just extremely grateful that others discovered what was happening and reported on it.

I never would've guessed that it was something so bizarre as Electron including specification-violating versions of random functions under some but not all circumstances.
