### ISSUE TITLE
google products like voice and hangouts go to a white screen with loading on bottom

### ISSUE THREAD

**Issue by landerson78** [TheGoddessInari/hamsket#292]
### Steps to reproduce

1. Open the hamsket app
2. Click on google voice tab
3. 

### Expected behavior

To load google voice

### Actual behavior
White screen with loading on bottom

### ENVIRONMENT

> Hamsket: v0.6.2-1

> OS: archlinux kernal 

> Arch: x64 

> BuildVersion: 5.15.7-zen1-1-zen

> Does this happen upstream: yes, no, unknown, or N/A
unknown

**Comment by TheGoddessInari** [comment]
This sounds like a similar old bug, working on trying to get an 0.6.3 release out. Nightly versions have fixes for this.

**Comment by landerson78** [comment]
k ty for all your hard work.

**Comment by landerson78** [comment]
I tried the appimage one of the Hamsket-0.6.3.AppImage and it went to the sign in page but gives this error

Couldn’t sign you in
This browser or app may not be secure. Learn more
Try using a different browser. If you’re already using a supported browser, you can try again to sign in.

**Comment by ikenichiro** [comment]
You can try by editing the service setting.
Click on `Advanced` and open `User Agent`, and add the below user agent string in `Custom User Agent`.
`Mozilla/5.0 (X11; Linux x86_64; rv:95.0) Gecko/20100101 Firefox/95.0`. 
It should solve the problem, which was natively implemented in the latest commit 0c6cda4.

**Comment by landerson78** [comment]
ty that worked. Ty for all your hard work you do a wonderful job.
