### ISSUE TITLE
Red banner: This browser won’t be supported starting March 1, 2022. Update your browser to keep using Slack.

### ISSUE THREAD

**Issue by alexthamm** [TheGoddessInari/hamsket#317]
### Steps to reproduce
1. Configure and login at Slack

### Expected behavior
Slack should be happy with the "browser".

### Actual behavior
Slack complains about an outdated browser.

### ENVIRONMENT
Version: 0.6.2
Platform: linux (x64)
Electron: 10.1.7
Chromium: 85.0.4183.121
Node: 12.16.3
BuildVersion: fd10375 (grafted, HEAD, tag: 0.6.2, origin/fd1037521df6214a1b6b3751242cfa409c4ac236) Thu, 10 Dec 2020 17:32:22 -0800

> Does this happen upstream: yes, no, unknown, or N/A

unknown

**Comment by Rohan-Thoma** [comment]
yeah same problem, it has officially stopped supporting slack as of today march 3rd

**Comment by jacr13** [comment]
It is a problem of the user agent used by Hamsket which is outdated.

A simple workaround it to go to the Hamsket tab, then on enabled services, click on the gear next to the slack service. A pop-up should open, go to Advanced > User Agent and on Custom User Agent paste some recent user agent like:

`Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36`

Finally, reload the service, and it should work normally again!

**Comment by alexthamm** [comment]
Thank you @jacr13.

However, I moved on to Ferdi (https://github.com/getferdi/ferdi) a few days ago as this project doesn't seem to be maintained anymore.

**Comment by Circuitsoft** [comment]
@alexthamm  Ferdi is more explicitly unmaintined, and Hamsket just got a release...

https://www.reddit.com/r/getferdi/comments/s8jhm2/just_removed_myself_as_a_ferdis_contributor/
